pluginManagement {
    repositories {
        **ARTIFACTORYREPOSITORY**
        maven {
            url 'https://maven.aliyun.com/repository/google'
            content {
                includeGroupByRegex 'com\\.android.*'
                includeGroupByRegex 'androidx.*'
                includeGroup 'com.google.testing.platform'
            }
        }
        maven { url 'https://maven.aliyun.com/repository/public' }
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}

include ':launcher', ':tuanjieLibrary'
**INCLUDES**

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        **ARTIFACTORYREPOSITORY**
        maven {
            url 'https://maven.aliyun.com/repository/google'
            content {
                includeGroupByRegex 'com\\.android.*'
                includeGroupByRegex 'androidx.*'
                includeGroup 'com.google.testing.platform'
            }
        }
        maven { url 'https://maven.aliyun.com/repository/public' }
        google()
        mavenCentral()
        flatDir { dirs "${project(':tuanjieLibrary').projectDir}/libs" }
    }
}
