package com.iohao.mmo;

import com.baidu.bjf.remoting.protobuf.ProtobufIDLGenerator;
import com.baidu.bjf.remoting.protobuf.annotation.Protobuf;
import com.baidu.bjf.remoting.protobuf.annotation.ProtobufClass;
import com.iohao.game.action.skeleton.annotation.ActionController;
import com.iohao.game.action.skeleton.annotation.ActionMethod;
import com.iohao.game.action.skeleton.core.CmdInfo;
import com.iohao.game.common.kit.ClassScanner;

import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Arrays;
import java.util.Comparator;
import java.util.HashSet;
import java.util.Set;

/** Exports the same jprotobuf field metadata used by the running game server. */
public final class UnityProtocolGenerate {
    public static void main(String[] args) throws Exception {
        Path output = Path.of(args.length == 0 ? "target/unity-protocol" : args[0]);
        Files.createDirectories(output);

        var messages = new ClassScanner("com.iohao.mmo", type -> !type.isEnum() && (
                type.isAnnotationPresent(ProtobufClass.class)
                        || Arrays.stream(type.getDeclaredFields())
                        .anyMatch(field -> field.isAnnotationPresent(Protobuf.class))))
                .listScan().stream().sorted(Comparator.comparing(Class::getName)).toList();
        Set<Class<?>> exported = new HashSet<>();
        Set<Class<?>> enums = new HashSet<>();
        StringBuilder schema = new StringBuilder("syntax = \"proto3\";\n"
                + "package lunhui;\noption csharp_namespace = \"Lunhui.Protocol\";\n\n");
        String syntaxHeader = "syntax=\"proto3\";\n";
        for (Class<?> message : messages) {
            String definition = ProtobufIDLGenerator.getIDL(message, exported, enums, true);
            if (definition == null) {
                continue;
            }
            if (!definition.startsWith(syntaxHeader)) {
                throw new IllegalStateException("Unexpected jprotobuf schema header: " + message.getName());
            }
            schema.append("// Java: ").append(message.getName()).append('\n');
            definition.substring(syntaxHeader.length()).lines()
                    .forEach(line -> schema.append(line.stripTrailing()).append('\n'));
            schema.append('\n');
        }
        Files.writeString(output.resolve("lunhui.proto"), schema, StandardCharsets.UTF_8);
        exportRoutes(output);
        System.out.println("Exported " + exported.size() + " message types to " + output.toAbsolutePath());
    }

    private static void exportRoutes(Path output) throws Exception {
        var actions = new ClassScanner("com.iohao.mmo", type -> type.isAnnotationPresent(ActionController.class))
                .listScan().stream().sorted(Comparator.comparing(Class::getName)).toList();
        StringBuilder routes = new StringBuilder("// <auto-generated>Java ioGame action annotations.</auto-generated>\n"
                + "namespace Lunhui.Protocol\n{\n    public static class ServerRoutes\n    {\n");
        for (Class<?> action : actions) {
            int module = action.getAnnotation(ActionController.class).value();
            var methods = Arrays.stream(action.getDeclaredMethods())
                    .filter(method -> method.isAnnotationPresent(ActionMethod.class))
                    .sorted(Comparator.comparing(method -> method.getName())).toList();
            for (var method : methods) {
                int command = method.getAnnotation(ActionMethod.class).value();
                routes.append("        public const int ").append(action.getSimpleName()).append('_')
                        .append(method.getName()).append(" = ")
                        .append(CmdInfo.of(module, command).getCmdMerge()).append(";\n");
            }
        }
        routes.append("    }\n}\n");
        Files.writeString(output.resolve("ServerRoutes.cs"), routes, StandardCharsets.UTF_8);
    }
}
